[package]
name = "mc-server-receptionist"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "net", "io-util"] }
serde = { version = "1", features = ["derive"]}
serde_json = { version = " 1" }
byteorder = { version = "1" }
