[package]
name = "mc-server-receptionist"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "net"] }
serde = { version = "1", features = ["derive"]}
byteorder = { version = "1" }
